# Generated by Django 3.1.2 on 2020-10-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('fullName', models.CharField(max_length=70)),
                ('gener', models.CharField(max_length=70)),
                ('correo', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=70)),
                ('rol', models.CharField(max_length=1)),
            ],
        ),
    ]
