# Generated by Django 3.1.2 on 2020-10-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0004_platillos2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platillos2',
        ),
    ]
